/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unitconverter;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Objects;
import javax.swing.ImageIcon;

/**
 *
 * @author ShadowFire
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
        public GUI() {
            initComponents();
            this.getContentPane().setBackground(new Color(54, 69, 79));
            Image logo  = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("logo.png"))).getImage();
            this.setIconImage(logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unit Converter");
        setBackground(new java.awt.Color(54, 69, 79));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(54, 69, 79));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Length:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer", "Meter", "Centimeter", "Millimeter", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer", "Meter", "Centimeter", "Millimeter", " " }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel3))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(54, 69, 79));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Weight:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("From:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("To:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogram", "Gram", "Milligram", "Pound" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogram", "Gram", "Milligram", "Pound" }));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel7))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Convert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(54, 69, 79));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Temperature:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("From:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("To:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Degree Celsius", "Fahrenheit", "Kelvin ", "Rankine" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Degree Celsius", "Fahrenheit", "Kelvin ", "Rankine" }));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel10))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Convert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(28, 28, 28)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String lengthFrom = (String)jComboBox1.getSelectedItem();
        String lengthTo = (String)jComboBox2.getSelectedItem();
        
        //KM to other
        if (lengthFrom.equals("Kilometer") && lengthTo.equals("Kilometer")) {
            double km = Double.parseDouble(jTextField1.getText());
            
            jTextField2.setText(String.valueOf(km));
        }
        else if (lengthFrom.equals("Kilometer") && lengthTo.equals("Meter")) {
            double km = Double.parseDouble(jTextField1.getText());
            double m = (double) (km * 1000);
            jTextField2.setText(String.valueOf(m));
        }
        else if (lengthFrom.equals("Kilometer") && lengthTo.equals("Centimeter")) {
            double km = Double.parseDouble(jTextField1.getText());
            double cm = (double) (km * 100000);
            jTextField2.setText(String.valueOf(cm));
        }
        else if (lengthFrom.equals("Kilometer") && lengthTo.equals("Millimeter")) {
            double km = Double.parseDouble(jTextField1.getText());
            double mm = (double) (km * 1000000);
            jTextField2.setText(String.valueOf(mm));
        }
        
        //M to other
        else if (lengthFrom.equals("Meter") && lengthTo.equals("Kilometer")) {
            double m = Double.parseDouble(jTextField1.getText());
            double km = (double) (m / 1000);
            jTextField2.setText(String.valueOf(km));
        }
        else if (lengthFrom.equals("Meter") && lengthTo.equals("Meter")) {
            double m = Double.parseDouble(jTextField1.getText());
            jTextField2.setText(String.valueOf(m));
        }
        else if (lengthFrom.equals("Meter") && lengthTo.equals("Centimeter")) {
            double m = Double.parseDouble(jTextField1.getText());
            double cm = (double) (m * 100);
            jTextField2.setText(String.valueOf(cm));
        }
        else if (lengthFrom.equals("Meter") && lengthTo.equals("Millimeter")) {
            double m = Double.parseDouble(jTextField1.getText());
            double mm = (double) (m * 1000);
            jTextField2.setText(String.valueOf(mm));
        }
        
        //CM to other
        else if (lengthFrom.equals("Centimeter") && lengthTo.equals("Kilometer")) {
            double cm = Double.parseDouble(jTextField1.getText());
            double km = (double) (cm / 10000);
            jTextField2.setText(String.valueOf(km));
        }
        else if (lengthFrom.equals("Centimeter") && lengthTo.equals("Centimeter")) {
            double cm = Double.parseDouble(jTextField1.getText());
            jTextField2.setText(String.valueOf(cm));
        }
        else if (lengthFrom.equals("Centimeter") && lengthTo.equals("Meter")) {
            double cm = Double.parseDouble(jTextField1.getText());
            double m = (double) (cm / 100);
            jTextField2.setText(String.valueOf(m));
        }
        else if (lengthFrom.equals("Centimeter") && lengthTo.equals("Millimeter")) {
            double cm = Double.parseDouble(jTextField1.getText());
            double mm = (double) (cm * 10);
            jTextField2.setText(String.valueOf(mm));
        }
        
        //MM to other
        else if (lengthFrom.equals("Millimeter") && lengthTo.equals("Kilometer")) {
            double mm = Double.parseDouble(jTextField1.getText());
            double km = (double) (mm / 1000000);
            jTextField2.setText(String.valueOf(km));
        }
        else if (lengthFrom.equals("Millimeter") && lengthTo.equals("Millimeter")) {
            double mm = Double.parseDouble(jTextField1.getText());
            jTextField2.setText(String.valueOf(mm));
        }
        else if (lengthFrom.equals("Millimeter") && lengthTo.equals("Meter")) {
            double mm = Double.parseDouble(jTextField1.getText());
            double m = (double) (mm / 1000);
            jTextField2.setText(String.valueOf(m));
        }
        else if (lengthFrom.equals("Millimeter") && lengthTo.equals("Centimeter")) {
            double mm = Double.parseDouble(jTextField1.getText());
            double cm = (double) (mm / 10);
            jTextField2.setText(String.valueOf(cm));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String weightFrom = (String)jComboBox3.getSelectedItem();
        String weightTo = (String)jComboBox4.getSelectedItem();
        
        //KG to others
        if (weightFrom.equals("Kilogram") && weightTo.equals("Kilogram")) {
            double kg = Double.parseDouble(jTextField3.getText());
            
            jTextField4.setText(String.valueOf(kg));
        }
        else if (weightFrom.equals("Kilogram") && weightTo.equals("Gram")){
            double kg = Double.parseDouble(jTextField3.getText());
            double g = (double) (kg * 1000);
            
            jTextField4.setText(String.valueOf(g));
        }
        else if (weightFrom.equals("Kilogram") && weightTo.equals("Milligram")){
            double kg = Double.parseDouble(jTextField3.getText());
            double mg = (double) (kg * 1000000);
            
            jTextField4.setText(String.valueOf(mg));
        }
        else if (weightFrom.equals("Kilogram") && weightTo.equals("Pound")){
            double kg = Double.parseDouble(jTextField3.getText());
            double p = (double) (kg * 2.20462);
            
            jTextField4.setText(String.valueOf(p));
        }
        
        //G to others
        else if (weightFrom.equals("Gram") && weightTo.equals("Gram")){
            double g = Double.parseDouble(jTextField3.getText());
            
            jTextField4.setText(String.valueOf(g));
        }
        else if (weightFrom.equals("Gram") && weightTo.equals("Kilogram")){
            double g = Double.parseDouble(jTextField3.getText());
            double kg = (double) (g / 1000);
            
            jTextField4.setText(String.valueOf(kg));
        }
        else if (weightFrom.equals("Gram") && weightTo.equals("Milligram")){
            double g = Double.parseDouble(jTextField3.getText());
            double mg = (double) (g * 1000);
            
            jTextField4.setText(String.valueOf(mg));
        }
        else if (weightFrom.equals("Gram") && weightTo.equals("Pound")){
            double g = Double.parseDouble(jTextField3.getText());
            double p = (double) (g * 0.00220462);
            
            jTextField4.setText(String.valueOf(p));
        }
        
        //MG to others
        else if (weightFrom.equals("Milligram") && weightTo.equals("Milligram")){
            double mg = Double.parseDouble(jTextField3.getText());
            
            jTextField4.setText(String.valueOf(mg));
        }
        else if (weightFrom.equals("Milligram") && weightTo.equals("Kilogram")){
            double mg = Double.parseDouble(jTextField3.getText());
            double kg = (double) (mg * 0.000001);
            
            jTextField4.setText(String.valueOf(kg));
        }
        else if (weightFrom.equals("Milligram") && weightTo.equals("Gram")){
            double mg = Double.parseDouble(jTextField3.getText());
            double g = (double) (mg * 0.001);
            
            jTextField4.setText(String.valueOf(g));
        }
        else if (weightFrom.equals("Milligram") && weightTo.equals("Pound")){
            double mg = Double.parseDouble(jTextField3.getText());
            double p = (double) (mg * 0.000002);
            
            jTextField4.setText(String.valueOf(p));
        }
        
        //P to others
        else if (weightFrom.equals("Pound") && weightTo.equals("Pound")){
            double p = Double.parseDouble(jTextField3.getText());
            
            jTextField4.setText(String.valueOf(p));
        }
        else if (weightFrom.equals("Pound") && weightTo.equals("Kilogram")){
            double p = Double.parseDouble(jTextField3.getText());
            double kg = (double) (p * 0.453592);
            
            jTextField4.setText(String.valueOf(kg));
        }
        else if (weightFrom.equals("Pound") && weightTo.equals("Gram")){
            double p = Double.parseDouble(jTextField3.getText());
            double g = (double) (p * 453.59237);
            
            jTextField4.setText(String.valueOf(g));
        }
        else if (weightFrom.equals("Pound") && weightTo.equals("Milligram")){
            double p = Double.parseDouble(jTextField3.getText());
            double mg = (double) (p * 453592.37);
            
            jTextField4.setText(String.valueOf(mg));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String tempFrom = (String)jComboBox5.getSelectedItem();
        String tempTo = (String)jComboBox6.getSelectedItem();
        
        //C to others
        if (tempFrom.equals("Degree Celsius") && tempTo.equals("Degree Celsius")) {
            double c = Double.parseDouble(jTextField5.getText());
            
            jTextField6.setText(String.valueOf(c));
        }
        else if (tempFrom.equals("Degree Celsius") && tempTo.equals("Fahrenheit")) {
            double c = Double.parseDouble(jTextField5.getText());
            double f = (double) (c * 9 / 5 + 32);
            
            jTextField6.setText(String.valueOf(f));
        }
        else if (tempFrom.equals("Degree Celsius") && tempTo.equals("Kelvin")) {
            double c = Double.parseDouble(jTextField5.getText());
            double k = (double) (c + 273.15);
            
            jTextField6.setText(String.valueOf(k));
        }
        else if (tempFrom.equals("Degree Celsius") && tempTo.equals("Rankine")) {
            double c = Double.parseDouble(jTextField5.getText());
            double r = (double) ((c + 273.15) * 9 / 5);
            
            jTextField6.setText(String.valueOf(r));
        }
        
        //F to others
        else if (tempFrom.equals("Fahrenheit") && tempTo.equals("Fahrenheit")) {
            double f = Double.parseDouble(jTextField5.getText());
            
            jTextField6.setText(String.valueOf(f));
        }
        else if (tempFrom.equals("Fahrenheit") && tempTo.equals("Kelvin")) {
            double f = Double.parseDouble(jTextField5.getText());
            double k = (double) ((f + 459.67) * 5 / 9);
            
            jTextField6.setText(String.valueOf(k));
        }
        else if (tempFrom.equals("Fahrenheit") && tempTo.equals("Degree Celsius")) {
            double f = Double.parseDouble(jTextField5.getText());
            double c = (double) ((f - 32) * 5 / 9);
            
            jTextField6.setText(String.valueOf(c));
        }
        else if (tempFrom.equals("Fahrenheit") && tempTo.equals("Rankine")) {
            double f = Double.parseDouble(jTextField5.getText());
            double r = (double) (f + 459.67);
            
            jTextField6.setText(String.valueOf(r));
        }
        
        //K to others
        else if (tempFrom.equals("Kelvin") && tempTo.equals("Kelvin")) {
            double f = Double.parseDouble(jTextField5.getText());
            
            jTextField6.setText(String.valueOf(f));
        }
        else if (tempFrom.equals("Kelvin") && tempTo.equals("Fahrenheit")) {
            double k = Double.parseDouble(jTextField5.getText());
            double f = (double) ((k * 9 / 5) - 459.67);
            
            jTextField6.setText(String.valueOf(f));
        }
        else if (tempFrom.equals("Kelvin") && tempTo.equals("Degree Celsius")) {
            double k = Double.parseDouble(jTextField5.getText());
            double c = (double) (k - 273.15);
            
            jTextField6.setText(String.valueOf(c));
        }
        else if (tempFrom.equals("Kelvin") && tempTo.equals("Rankine")) {
            double k = Double.parseDouble(jTextField5.getText());
            double r = (double) (k * 9 / 5);
            
            jTextField6.setText(String.valueOf(r));
        }
        
        //R to others
        else if (tempFrom.equals("Rankine") && tempTo.equals("Rankine")) {
            double f = Double.parseDouble(jTextField5.getText());
            
            jTextField6.setText(String.valueOf(f));
        }
        else if (tempFrom.equals("Rankine") && tempTo.equals("Fahrenheit")) {
            double r = Double.parseDouble(jTextField5.getText());
            double f = (double) (r - 459.67);
            
            jTextField6.setText(String.valueOf(f));
        }
        else if (tempFrom.equals("Rankine") && tempTo.equals("Degree Celsius")) {
            double r = Double.parseDouble(jTextField5.getText());
            double c = (double) ((r * 5 / 9) - 273.15);
            
            jTextField6.setText(String.valueOf(c));
        }
        else if (tempFrom.equals("Rankine") && tempTo.equals("Kelvin")) {
            double r = Double.parseDouble(jTextField5.getText());
            double k = (double) (r * 5 / 9);
            
            jTextField6.setText(String.valueOf(k));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }
    
    public void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
